#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

DATE_TAG="$(date '+%Y-%m-%d')"
REPORT_FILE="$OUTPUT_DIR/linux_consolidated_report_${DATE_TAG}.txt"

monitor_runs="$(grep -c '\[MONITOR\]' "$SCHEDULE_LOG" 2>/dev/null || true)"
file_runs="$(grep -c '\[FILES\]' "$SCHEDULE_LOG" 2>/dev/null || true)"
maintenance_runs="$(grep -c '\[MAINT\]' "$SCHEDULE_LOG" 2>/dev/null || true)"
report_runs="$(grep -c '\[REPORT\]' "$SCHEDULE_LOG" 2>/dev/null || true)"
error_count="$(grep -ci '\[ERROR\]' "$SCHEDULE_LOG" 2>/dev/null || true)"
backup_count="$(find "$BACKUP_DIR" -maxdepth 1 -type f -name '*.tar.gz' | wc -l | tr -d ' ')"

latest_snapshot="$(ls -1t "$OUTPUT_DIR"/system_snapshot_*.txt 2>/dev/null | head -n 1 || true)"

overall_status="HEALTHY"
if [[ "$error_count" -gt 0 ]]; then
  overall_status="NEEDS_ATTENTION"
fi

{
  echo "SMART SYSTEM AUTOMATION SUITE - LINUX REPORT"
  echo "Generated at: $(timestamp)"
  echo "Generated by user: $(whoami)"
  echo
  echo "1) SYSTEM RESOURCE USAGE SUMMARY"
  if [[ -n "$latest_snapshot" && -f "$latest_snapshot" ]]; then
    echo "Latest snapshot file: $latest_snapshot"
    echo
    echo "Memory usage excerpt:"
    awk '/---- Memory Usage ----/{flag=1;next}/---- Disk Utilization ----/{flag=0}flag' "$latest_snapshot" | head -n 6 || true
    echo
    echo "Disk utilization excerpt:"
    awk '/---- Disk Utilization ----/{flag=1;next}/---- Network Activity/{flag=0}flag' "$latest_snapshot" | head -n 8 || true
  else
    echo "No monitoring snapshot found yet."
  fi
  echo
  echo "2) BACKUP OPERATIONS"
  echo "Total backup archives available: $backup_count"
  echo "Latest backup manifest:"
  ls -1t "$OUTPUT_DIR"/backup_manifest_*.csv 2>/dev/null | head -n 1 || echo "No backup manifest found."
  echo
  echo "3) FREQUENCY OF SCHEDULED EXECUTIONS"
  echo "Monitoring runs: $monitor_runs"
  echo "File management runs: $file_runs"
  echo "Maintenance runs: $maintenance_runs"
  echo "Report generations: $report_runs"
  echo
  echo "4) OVERALL SYSTEM STATUS"
  echo "Status: $overall_status"
  echo "Errors seen in schedule log: $error_count"
  echo
  echo "5) LOG REFERENCES"
  echo "Schedule log: $SCHEDULE_LOG"
  echo "Monitoring logs: $LOG_DIR/system_monitor_*.log"
  echo "File management logs: $LOG_DIR/file_management_*.log"
  echo "Maintenance logs: $LOG_DIR/maintenance_*.log"
} > "$REPORT_FILE"

append_schedule_log "REPORT" "SUCCESS" "Consolidated report generated at $REPORT_FILE"
echo "Report generated: $REPORT_FILE"
